modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/XGJSJS/rsgauges/issues/"
license = "MIT"

[[mods]]
modId = "rsgauges"
version = "${version}"
displayName = "Gauges and Switches"
authors = "wilechaote"
description = '''
Adds redstone metering gauges, levers, buttons, pressure plates, and all sorts of other sensors and detector switches to the game.
'''
logoFile = "logo.png"
displayURL = "https://github.com/XGJSJS/rsgauges"

[[dependencies.rsgauges]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rsgauges]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rsgauges]]
modId = "architectury"
mandatory = true
versionRange = "[9.0.8,)"
ordering = "AFTER"
side = "BOTH"
